spring:
  application:
    name: api-gateway

server:
  port: 5555

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

#zuul:
#  routes:
#    a-hello: /api-a/**
#    serviceOfCloud-hello: /api-b/**
